---
config:
  layout: fixed
  theme: mc
---
flowchart TB
 subgraph Agents["Agents"]
        B{"INQUIRY/ORDER"}
        A["Orchestration Agent"]
        C["Inventory Agent"]
        D["Inventory Agent"]
        E["Quoting Agent"]
        F["Ordering Agent"]
        G["Invoice Agent"]
        I["Advisory Report"]
        H["Business Advisory Agent"]
  end
 subgraph Outcomes["Outcomes"]
        J["Inventory Response"]
        K["Quote Response"]
        L["Sales Response"]
        M["Invoice Response"]
        N["Advisory Response"]
  end
    A -- Request Classification --> B
    B -- INQUIRY --> C
    B -- ORDER --> D
    D -- Quote --> E
    E -- Order --> F
    F -- Invoice --> G
    H -- Recommendations --> I
    J --> C
    L --> F
    M --> G
    N --> H
    A --> B
    B --> C & D
    D --> E
    E --> F
    F --> G
    G --> M
    H --> I & N
    K --> E